### ISSUE TITLE
`c4test` segfaults with e.g. `basic1.c4m`

### ISSUE THREAD

**Issue by ee7** [crashappsec/libcon4m#37]
Running `c4test` sometimes works:

```text
$ build/c4test tests/basic1.c4m
info: Compiling from: tests/basic1.c4m
Processing module tests/basic1.c4m

[...]

Heap Usage: 27932 kb of 131072 kb (103139 kb free)
 Copied 7960 allocation records. Trashed 32380 records.
New Usage: 6304 kb (21627 kb collected)
```

and sometimes segfaults:

```console
$ build/c4test tests/basic1.c4m
info: Compiling from: tests/basic1.c4m
zsh: segmentation fault (core dumped)  build/c4test tests/basic1.c4m
```

It looks like this was introduced by 1e6a017302e4438034a300f5a21e0eb2aeb723c8 (the codegen PR, https://github.com/crashappsec/libcon4m/pull/31). The commit before that seems OK.

The segfaults still occur with https://github.com/crashappsec/libcon4m/pull/36.

**Comment by viega** [comment]
I cannot reproduce locally; please provide a stack trace.

**Comment by viega** [comment]
Well, there is no free handler being set anywhere via `con4m`, so that branch shouldn't be running, period. That means the underlying object is somehow getting corrupted somehow (scribbling over the `free_hander` field). I say that because, even if not using `calloc()`, `hatrack_dict_init` is explicit about zeroing out fields. Unfortunately, when I add a watchpoint in a debugger, I see no corruption whatsoever.

So if you can track down any more info, that would be very helpful.

**Comment by viega** [comment]
Okay, I found a candidate for the culprit.

Can you try, in `c4m_collect_arena` (gc.c), change from this:
```
    if (r == NULL) {
        r = c4m_rc_ref(global_roots);
    }
```
to this:
```
    if (r == NULL) {
        r = global_roots;
    }

    c4m_rc_ref(r);
```

It's definitely wrong and have made the change locally; even though I can't reproduce directly, I feel pretty good about it being the issue.
