### ISSUE TITLE
SIGSEGV: right shift of a negative number

### ISSUE THREAD

**Issue by ee7** [crashappsec/libcon4m#71]
With:

- libcon4m b4fdc8e2e70b0ef18a554562702e2db1e0c9aff0
- The `macos-14` GitHub runner (aarch64, with clang 15).

### Example

```text
x = -1

x >>= 0
print(x)
```

### Expected behavior

Outputs -1.

### Current behavior

Crashes.

**Comment by viega** [comment]
I didn't change anything here, but it seems to be working using my current PR. 

There were lots of indirect issues that could pop up that were really due to what I found and fixed with my new memory checking stuff (in #78). Unfortunately, ASAN didn't detect it, even when I integrated with their API.

But this was probably a consequence.
